import type { GameState } from '../game/simulation';
import { buildingCost,BUILDING_KEYS,getRates,MAX_BUILDING_LEVEL,workerSlots } from '../game/simulation';
import { JOURNEY_BRANCHES,LEGACIES,legacyLevel,legacyCost,legacyLock,PREPARATIONS,TRIALS,trialProgress,type JourneyBranch } from '../game/ancestralJourney';
import { ERA_GROWTH } from '../game/tribe';
import { glyphSVG,type AnimalId } from '../render/spiritGlyphs';
import { portraitHTML } from '../render/portrait';
import { characters } from '../data/characters';

export const uiEsc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const uiIcon=(s:string)=>`<i data-lucide="${s}"></i>`;
export const provisionCost=(cost:Record<string,number>)=>Object.entries(cost).filter(([,n])=>n>0).map(([id,n])=>{const label=({wood:'Madeira',food:'Alimento',stone:'Pedra',spirit:'Espírito'} as Record<string,string>)[id];return `<span title="${label}" aria-label="${n} ${label}">${uiIcon(({wood:'trees',food:'beef',stone:'mountain',spirit:'flame'} as Record<string,string>)[id])}${n.toLocaleString('pt-BR')}</span>`;}).join('');
const attrs=(cost:Record<string,number>)=>`data-cost='${JSON.stringify(cost)}'`;
export function trialMarkup(s:GameState) {
  const t=TRIALS.find(t=>t.id===s.journey.trial?.id),progress=trialProgress(s);
  return `<section class="ancestral-trial"><div><p class="eyebrow">UM PROPÓSITO PARA A TRIBO</p><h2>${t?t.name:'Escolha o próximo desafio'}</h2><p>${t?t.text:'Combata, explore a mata ou conduza cerimônias. Cada desafio rende conhecimento para seus legados.'}</p></div>${t?`<div class="trial-progress"><strong>${progress}<small> / ${t.goal}</small></strong><progress max="${t.goal}" value="${progress}" aria-label="Progresso de ${t.name}"></progress><span>+${t.reward} de conhecimento</span><button class="primary" data-claim-trial ${s.paused||progress<t.goal?'disabled':''}>${uiIcon('sparkles')}Receber conhecimento</button></div>`:''}<div class="trial-options">${TRIALS.map(d=>`<button data-accept-trial="${d.id}" aria-pressed="${t?.id===d.id}" ${s.paused||t?.id===d.id?'disabled':''}>${uiIcon(d.icon)}<span>${d.name}<small>${d.goal} ${d.id==='combat'?'vitórias':d.id==='hunt'?'caçada':'cerimônia'} · +${d.reward} conhecimento</small></span></button>`).join('')}</div>${t?'<p class="ancestral-note">Trocar de desafio reinicia apenas o progresso do desafio ativo. Recompensas recebidas e legados são mantidos.</p>':''}</section>`;
}
export function preparationsMarkup(s:GameState,compact=false) {
  const j=s.journey;
  return `<div class="preparation-explainer"><h2>O que levamos para a batalha</h2><p>Escolha até dois preparativos. Cada expedição iniciada consome uma carga dos selecionados; ataques à tribo não gastam este estoque. O efeito dura a batalha inteira.</p><strong>${j.selected.length} / 2 selecionados</strong></div><div class="preparation-grid ${compact?'compact':''}">${PREPARATIONS.map(d=>{const stock=j.preparations[d.id]??0,selected=j.selected.includes(d.id),locked=s.villageLevel<d.era;return `<article class="preparation-card ${selected?'selected':''}"><div class="preparation-title">${uiIcon(d.icon)}<h3>${d.name}</h3><span>${stock} carga${stock===1?'':'s'}</span></div><p>${d.text}</p><div class="cost">${provisionCost(d.cost)}</div><div class="preparation-actions"><button class="outline-button" data-prepare-expedition="${d.id}" ${attrs(d.cost)} data-max="${locked||stock>=5}" data-lock-battle="1">${locked?`Era ${d.era}`:'Preparar +1'}</button><button class="${selected?'selected':''}" data-select-preparation="${d.id}" aria-pressed="${selected}" data-lock-battle="1" ${s.paused||!stock||(!selected&&j.selected.length>=2)?'disabled':''}>${selected?'Selecionado':'Levar'}</button></div></article>`;}).join('')}</div>`;
}
export function journeyPage(s:GameState,tab:'paths'|'provisions'|'preparations',branch:JourneyBranch) {
  const b=JOURNEY_BRANCHES[branch],need=ERA_GROWTH[s.villageLevel-1];
  const header=`<header class="ancestral-heading"><div><p class="eyebrow">ERA ${s.villageLevel} · ${s.progress}/30 EXPEDIÇÕES</p><h1>O caminho da sua tribo.</h1><p>Cada batalha ensina. Cada cerimônia fortalece o vínculo. Escolha o que levar adiante.</p></div><div class="knowledge-counter">${uiIcon('sparkles')}<strong>${s.journey.knowledge}</strong><span>conhecimento<br>ancestral</span></div></header>`;
  if(tab==='preparations')return header+preparationsMarkup(s);
  if(tab==='provisions'){
    const names={lumber:'Ofício da madeira',hunt:'Provisões da mata',quarry:'Pedra ancestral',shrine:'Oferendas do círculo',forge:'Forja de Osso',cura:'Maloca das cerimônias'},rates=getRates(s);
    return header+`<div class="provisions-intro"><h2>Ofícios que sustentam a jornada</h2><p>A produção é automática e continua por até 12 horas fora do jogo. As melhorias são imediatas. Companheiros na reserva podem ajudar um ofício para ganhar experiência; eles ficam fora da formação enquanto trabalham.</p><button class="outline-button" data-action="hunts">Abrir caçadas</button><button class="outline-button" data-action="cura">Abrir rituais</button></div><div class="provision-grid">${BUILDING_KEYS.map(id=>{const level=s.buildings[id],c=buildingCost(id,level),resource=({lumber:'wood',hunt:'food',quarry:'stone',shrine:'spirit'} as const)[id as 'lumber'|'hunt'|'quarry'|'shrine'];const workers=s.heroes.filter(h=>h.work===id);return `<article><p class="eyebrow">NÍVEL ${level} / ${MAX_BUILDING_LEVEL}</p><h3>${names[id]}</h3><p>${resource?`<b data-journey-rate="${resource}">+${rates[resource].toFixed(1)}/s</b>`:id==='forge'?'Produz componentes e combina equipamentos.':'Abre e sustenta as cerimônias da tribo.'}</p><button class="outline-button" data-upgrade-workshop="${id}" ${attrs(c)} data-max="${level>=MAX_BUILDING_LEVEL||(id==='forge'&&s.villageLevel<2)}">${level?'Melhorar ofício':'Abrir ofício'}<span class="cost">${provisionCost(c)}</span></button><div class="workshop-workers"><h4>Ajudantes · ${workers.length}/${workerSlots(s,id)}</h4>${workers.map(h=>`<button data-unassign="${h.uid}">${portraitHTML(characters.find(c=>c.id===h.characterId)!,h.stars)}${characters.find(c=>c.id===h.characterId)!.name} · retirar</button>`).join('')}${level&&workers.length<workerSlots(s,id)?`<select aria-label="Ajudante para ${names[id]}" data-workshop-hero="${id}"><option value="">Escolher companheiro disponível…</option>${s.heroes.filter(h=>!h.away&&!h.work&&h.slot===null).map(h=>`<option value="${h.uid}">${characters.find(c=>c.id===h.characterId)!.name}</option>`).join('')}</select>`:''}</div></article>`;}).join('')}</div>`;
  }
  return header+trialMarkup(s)+`<div class="ancestral-layout"><section class="legacy-map"><nav class="legacy-branches" aria-label="Caminhos ancestrais">${Object.entries(JOURNEY_BRANCHES).map(([id,d])=>`<button data-journey-branch="${id}" aria-pressed="${id===branch}" style="--path:${d.color}">${glyphSVG(d.animal as AnimalId,d.color)}<span>${d.name}</span></button>`).join('')}</nav><div class="legacy-path" style="--path:${b.color}"><div class="legacy-path-heading">${glyphSVG(b.animal as AnimalId,b.color)}<div><h2>${b.name}</h2><p>${b.description}</p></div></div><ol>${LEGACIES.filter(d=>d.branch===branch).map(d=>{const level=legacyLevel(s,d.id),lock=legacyLock(s,d),cost=legacyCost(level);return `<li class="${level?'learned':''} ${lock?'locked':''}"><div class="legacy-node">${uiIcon(d.icon)}</div><article><div><h3>${d.name}</h3><span>${level}/3</span></div><p>${d.text}</p><div class="legacy-levels" aria-label="${level} de 3 níveis">${[1,2,3].map(i=>`<i class="${i<=level?'on':''}"></i>`).join('')}</div><button class="outline-button" data-learn-legacy="${d.id}" ${s.paused||lock||s.journey.knowledge<cost?'disabled':''} data-lock-battle="1">${lock||`Aprender · ${cost} conhecimento`}</button></article></li>`;}).join('')}</ol></div></section><aside class="journey-guidance"><p class="eyebrow">PRÓXIMO PASSO</p><h2>Fortaleça o vínculo.</h2><p>Heróis evoluem quando experiência e ritualística alcançam os requisitos juntos. Legados apoiam a jornada e não substituem essa evolução.</p><button class="primary" data-action="tribe">Cuidar dos companheiros ${uiIcon('arrow-right')}</button><button class="outline-button" data-action="cura">Conduzir uma cerimônia</button><button class="outline-button" data-action="army-coach">Preparar a formação</button>${need?`<div class="era-next"><h3>Próxima era</h3><p>Um herói com experiência ${need.level} e ritual ${need.ritualLevel}, mais as provisões da ascensão.</p><button class="text-button" data-action="village-upgrade">Conferir requisitos de ascensão</button></div>`:'<p>A tribo alcançou a Era dos Ancestrais.</p>'}${s.journey.migrated?'<p class="ancestral-note">O progresso anterior foi preservado. Obras de ofícios pagas foram entregues; ordens civis pendentes foram reembolsadas e investimentos de RTS viraram conhecimento.</p>':''}<p class="ancestral-note">Legados e conhecimento atravessam o renascimento no Grande Totem. Preparativos consumíveis recomeçam vazios.</p></aside></div>`;
}
