import type { GameState } from '../game/simulation';
import { blessingLock,JOURNEY_BRANCHES,LEGACIES,legacyLevel,legacyCost,legacyLock,PREPARATIONS,TRIALS,trialProgress,type JourneyBranch } from '../game/ancestralJourney';
import { ERA_GROWTH } from '../game/tribe';
import { glyphSVG,type AnimalId } from '../render/spiritGlyphs';
import { portraitHTML } from '../render/portrait';
import { characters } from '../data/characters';

export const uiEsc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const uiIcon=(s:string)=>`<i data-lucide="${s}"></i>`;
export function trialMarkup(s:GameState) {
  const t=TRIALS.find(t=>t.id===s.journey.trial?.id),progress=trialProgress(s);
  return `<section class="ancestral-trial"><div><p class="eyebrow">UM PROPÓSITO PARA A TRIBO</p><h2>${t?t.name:'Escolha o próximo desafio'}</h2><p>${t?t.text:'Combata, explore a mata ou conduza cerimônias. Cada desafio rende conhecimento para seus legados.'}</p></div>${t?`<div class="trial-progress"><strong>${progress}<small> / ${t.goal}</small></strong><progress max="${t.goal}" value="${progress}" aria-label="Progresso de ${t.name}"></progress><span>+${t.reward} de conhecimento</span><button class="primary" data-claim-trial ${s.paused||progress<t.goal?'disabled':''}>${uiIcon('sparkles')}Receber conhecimento</button></div>`:''}<div class="trial-options">${TRIALS.map(d=>`<button data-accept-trial="${d.id}" aria-pressed="${t?.id===d.id}" ${s.paused||t?.id===d.id?'disabled':''}>${uiIcon(d.icon)}<span>${d.name}<small>${d.goal} ${d.id==='combat'?'vitórias':d.id==='hunt'?'caçada':'cerimônia'} · +${d.reward} conhecimento</small></span></button>`).join('')}</div>${t?'<p class="ancestral-note">Trocar de desafio reinicia apenas o progresso do desafio ativo. Recompensas recebidas e legados são mantidos.</p>':''}</section>`;
}
export function preparationsMarkup(s:GameState,compact=false) {
  const j=s.journey;
  return `<div class="preparation-explainer"><h2>Bênçãos que acompanham sua tribo</h2><p>Os rituais desbloqueiam estas afinidades. Escolha até duas: elas permanecem nas próximas batalhas e podem ser trocadas entre os combates.</p><strong>${j.selected.length} / 2 ativas</strong></div><div class="preparation-grid ${compact?'compact':''}">${PREPARATIONS.map(d=>{
    const selected=j.selected.includes(d.id),lock=blessingLock(s,d.id);
    return `<article class="preparation-card ${selected?'selected':''}"><div class="preparation-title">${uiIcon(d.icon)}<h3>${d.name}</h3><span>${selected?'Ativa':lock?'A descobrir':'Aprendida'}</span></div><p>${d.text}</p><p class="ancestral-note">${lock??'Pode acompanhar todas as expedições.'}</p><button class="outline-button" data-select-preparation="${d.id}" aria-pressed="${selected}" data-lock-battle="1" ${s.paused||!!lock||(!selected&&j.selected.length>=2)?'disabled':''}>${selected?'Retirar bênção':'Ativar bênção'}</button></article>`;
  }).join('')}</div>`;
}
export function journeyPage(s:GameState,tab:'paths'|'preparations',branch:JourneyBranch) {
  const b=JOURNEY_BRANCHES[branch],need=ERA_GROWTH[s.era-1];
  const header=`<header class="ancestral-heading"><div><p class="eyebrow">ERA ${s.era} · ${s.progress}/30 EXPEDIÇÕES</p><h1>O caminho da sua tribo.</h1><p>Cada batalha ensina. Cada cerimônia fortalece o vínculo. Escolha o que levar adiante.</p></div><div class="knowledge-counter">${uiIcon('sparkles')}<strong>${s.journey.knowledge}</strong><span>conhecimento<br>ancestral</span></div></header>`;
  if(tab==='preparations')return header+preparationsMarkup(s);
  return header+trialMarkup(s)+`<div class="ancestral-layout"><section class="legacy-map"><nav class="legacy-branches" aria-label="Caminhos ancestrais">${Object.entries(JOURNEY_BRANCHES).map(([id,d])=>`<button data-journey-branch="${id}" aria-pressed="${id===branch}" style="--path:${d.color}">${glyphSVG(d.animal as AnimalId,d.color)}<span>${d.name}</span></button>`).join('')}</nav><div class="legacy-path" style="--path:${b.color}"><div class="legacy-path-heading">${glyphSVG(b.animal as AnimalId,b.color)}<div><h2>${b.name}</h2><p>${b.description}</p></div></div><ol>${LEGACIES.filter(d=>d.branch===branch).map(d=>{const level=legacyLevel(s,d.id),lock=legacyLock(s,d),cost=legacyCost(level);return `<li class="${level?'learned':''} ${lock?'locked':''}"><div class="legacy-node">${uiIcon(d.icon)}</div><article><div><h3>${d.name}</h3><span>${level}/3</span></div><p>${d.text}</p><div class="legacy-levels" aria-label="${level} de 3 níveis">${[1,2,3].map(i=>`<i class="${i<=level?'on':''}"></i>`).join('')}</div><button class="outline-button" data-learn-legacy="${d.id}" ${s.paused||lock||s.journey.knowledge<cost?'disabled':''} data-lock-battle="1">${lock||`Aprender · ${cost} conhecimento`}</button></article></li>`;}).join('')}</ol></div></section><aside class="journey-guidance"><p class="eyebrow">PRÓXIMO PASSO</p><h2>Fortaleça o vínculo.</h2><p>Heróis evoluem quando experiência e ritualística alcançam os requisitos juntos. Legados apoiam a jornada e não substituem essa evolução.</p><button class="primary" data-action="tribe">Cuidar dos companheiros ${uiIcon('arrow-right')}</button><button class="outline-button" data-action="cura">Conduzir uma cerimônia</button><button class="outline-button" data-action="army-coach">Preparar a formação</button>${need?`<div class="era-next"><h3>Próxima era</h3><p>Um herói com experiência ${need.level} e ritual ${need.ritualLevel}.</p><button class="text-button" data-action="village-upgrade">Conferir requisitos de ascensão</button></div>`:'<p>A tribo alcançou a Era dos Ancestrais.</p>'}${s.journey.migrated?'<p class="ancestral-note">Seu progresso foi preservado. Ofícios e preparativos antigos viraram conhecimento ancestral.</p>':''}<p class="ancestral-note">Legados e conhecimento atravessam o renascimento no Grande Totem. Bênçãos são escolhidas novamente conforme a nova tribo aprende rituais.</p></aside></div>`;
}
