import { characters } from '../data/characters';
import type { GameState, Hero, Resources } from '../game/simulation';
import { builderCount, CITIZEN_JOBS, constructionCount, INFRASTRUCTURE, orderTitle, populationCap, raidProtection, RESEARCH, researchCost, TERRITORIES, territoryById, territoryLock, trainingCost, villagePlots, type CitizenJob, type InfrastructureId, type ResearchId } from '../game/settlement';
import { activeArmy, armySuggestions, armyWarnings, itemAdvice, nearTraits, recommendedParty, ROLE_GUIDE, roleOf } from '../game/armyAdvisor';
import { enemyAdvice } from '../game/armyAdvisor';
import { TRAIT_RULES, traitStatus, countTraits } from '../game/synergies';
import { itemById } from '../game/items';
import { SETTLEMENT_MILESTONES } from '../game/settlement';
import { portraitHTML } from '../render/portrait';

const esc=(text:string)=>text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const icon=(name:string)=>`<i data-lucide="${name}"></i>`;
const RESOURCE_NAMES={wood:'madeira',food:'alimento',stone:'pedra',spirit:'espírito'};
export const civicCost=(cost:Resources)=>Object.entries(cost).filter(([,n])=>n>0).map(([r,n])=>`<span>${icon(CITIZEN_JOBS[r as CitizenJob].icon)}${Math.ceil(n).toLocaleString('pt-BR')}</span>`).join('');
const costAttr=(cost:Resources)=>`data-cost='${JSON.stringify(cost)}'`;
const heading=(title:string,kicker:string,description:string)=>`<button class="panel-close icon-button" data-action="panel-close" aria-label="Recolher painel">${icon('x')}</button><p class="eyebrow">${kicker}</p><h2>${title}</h2><p class="civic-intro">${description}</p>`;
export function orderQueue(s:GameState):string {
  return `<section class="village-orders"><h3>Ordens em andamento <small>${s.settlement.orders.length}</small></h3>${s.settlement.orders.length?s.settlement.orders.map(o=>`<div class="village-order"><div><b>${orderTitle(o)}</b><span data-until="${o.until}"></span></div><progress data-order-progress="${o.id}" max="1" value="${(s.clock-o.started)/(o.until-o.started)}" aria-label="Progresso de ${orderTitle(o)}"></progress><button class="text-button" data-cancel-order="${o.id}" title="Devolve 80% dos recursos">Cancelar · 80% de volta</button></div>`).join(''):'<p class="muted">Construtores, reconhecimento, preparação de aldeões e pesquisas continuam enquanto você está fora.</p>'}</section>`;
}
export function economyPanel(s:GameState,selected:number|null):string {
  const v=s.settlement,c=v.citizens.find(c=>c.id===selected),busy=c&&v.orders.find(o=>o.citizenId===c.id);
  return heading(c?`Aldeão ${c.id}`:'Uma aldeia viva','COMANDO DA ALDEIA',c?'Escolha um ofício e depois selecione um lugar no mapa. Aldeões produzem recursos; heróis mantêm suas duas trilhas de crescimento.':'Prepare aldeões, distribua os ofícios e reserve construtores para as próximas obras.')+
    `<div class="population-meter"><strong>${v.citizens.length}<small> / ${populationCap(s)}</small></strong><span>Aldeões da tribo<br><small>${builderCount(s)-constructionCount(s)} construtor(es) livre(s)</small></span></div>
    ${c?`<p class="citizen-selection">${busy?'Reconhecendo a mata. Retorna ao ofício ao concluir.':`Ofício atual: ${CITIZEN_JOBS[c.job].name}`}</p><div class="citizen-command">${Object.entries(CITIZEN_JOBS).map(([job,d])=>`<button data-citizen-job="${job}" data-citizen-id="${c.id}" ${busy?'disabled':''} aria-pressed="${c.job===job}">${icon(d.icon)}${d.name}</button>`).join('')}</div><button class="text-button" data-citizen-clear>Voltar à população</button>`:
    `<div class="citizen-distribution">${Object.entries(CITIZEN_JOBS).map(([job,d])=>`<div><span>${icon(d.icon)}${d.name}</span><div><button data-citizen-adjust="${job}:-1" aria-label="Retirar aldeão de ${d.name}" ${job==='idle'||!v.citizens.some(c=>c.job===job)?'disabled':''}>−</button><b>${v.citizens.filter(c=>c.job===job).length}</b><button data-citizen-adjust="${job}:1" aria-label="Adicionar aldeão a ${d.name}" ${job==='idle'?'disabled':''}>+</button></div></div>`).join('')}</div>`}
    <button class="primary" data-train-citizen ${costAttr(trainingCost())} data-max="${v.citizens.length>=populationCap(s)||v.orders.some(o=>o.kind==='train')}">${icon('user-plus')}Preparar aldeão <span class="cost">${civicCost(trainingCost())}</span></button><p class="civic-note">30 segundos de preparação. Novos aldeões chegam disponíveis. Mais moradias abrem vagas.</p>
    <div class="civic-links"><button data-rts-mode="construct">${icon('hammer')}Erguer construções</button><button data-rts-mode="territory">${icon('map')}Explorar fronteiras</button></div>${orderQueue(s)}
    <section class="village-milestones"><h3>Marcos da aldeia</h3>${SETTLEMENT_MILESTONES.filter(m=>!v.milestones.includes(m.id)).slice(0,3).map(m=>`<article><b>${m.name}</b><p>${m.hint}</p><small>${civicCost(m.reward)}</small>${m.done(s)?`<button class="outline-button" data-settlement-milestone="${m.id}">Receber recursos</button>`:''}</article>`).join('')||'<p>Todos os marcos desta jornada foram concluídos.</p>'}</section>
    ${v.log.length?`<details class="civic-log"><summary>Diário da aldeia</summary>${v.log.slice(-5).reverse().map(e=>`<p>${esc(e.text)}</p>`).join('')}</details>`:''}`;
}
export function constructionPanel(s:GameState,placement:InfrastructureId|null):string {
  const plots=villagePlots(s).filter(p=>!s.settlement.sites[p.id]&&!s.settlement.orders.some(o=>o.plot===p.id));
  return heading('Erga a aldeia','CONSTRUÇÃO NO MAPA','Escolha uma construção e toque em um terreno livre. Cada obra ocupa um construtor até a conclusão.')+
  `<div class="construction-catalog">${Object.entries(INFRASTRUCTURE).map(([id,d])=>`<button data-infrastructure="${id}" class="${placement===id?'selected':''}" ${s.villageLevel<d.era?'disabled':''}><span>${icon(({housing:'tent',store:'warehouse',farm:'sprout',watchtower:'tower-control',market:'handshake'} as Record<string,string>)[id])}<b>${d.name}</b></span><small>${d.description}</small><span class="cost">${civicCost(d.cost)} · ${d.seconds}s${s.villageLevel<d.era?` · Era ${d.era}`:''}</span></button>`).join('')}</div>
  ${placement?`<section class="placement-command"><h3>${INFRASTRUCTURE[placement].name}</h3><p>Os terrenos livres estão marcados no mapa.</p><label>Terreno<select id="rts-plot" aria-label="Terreno para construir">${plots.map(p=>`<option value="${p.id}">${p.id.startsWith('hearth')?`Clareira central · ${p.id.slice(-1)}`:territoryById(p.id.replace(/-1$/,''))?.name}</option>`).join('')}</select></label><button class="primary" data-build-on-plot ${costAttr(INFRASTRUCTURE[placement].cost)} data-max="${!plots.length||constructionCount(s)>=builderCount(s)}">Construir no terreno</button><button class="text-button" data-placement-cancel>Cancelar seleção</button></section>`:'<p class="civic-note">Reconhecer e ocupar a mata abre novos terrenos para construções.</p>'}${orderQueue(s)}`;
}
export function territoryPanel(s:GameState,selected:string):string {
  const t=territoryById(selected)??TERRITORIES[0],v=s.settlement,owned=v.claimed.includes(t.id),seen=v.discovered.includes(t.id),order=v.orders.find(o=>o.target===t.id&&['scout','claim'].includes(o.kind)),lock=territoryLock(s,t);
  return heading('Além da clareira','TERRITÓRIOS DA TRIBO','Reconheça a mata, estabeleça postos e amplie o território. Alguns caminhos exigem vitórias nas expedições.')+
  `<nav class="territory-list" aria-label="Territórios">${TERRITORIES.map(region=>`<button data-territory="${region.id}" aria-pressed="${region.id===t.id}">${icon(CITIZEN_JOBS[region.resource].icon)}<span>${region.name}<small>${v.claimed.includes(region.id)?'Posto estabelecido':v.discovered.includes(region.id)?'Reconhecido':`Era ${region.era} · reconhecer`}</small></span></button>`).join('')}</nav>
  <article class="territory-detail"><h3>${t.name}</h3><p>${t.description}</p><p>Posto: +12% de produção dos aldeões de ${RESOURCE_NAMES[t.resource]}, +0,15 ${RESOURCE_NAMES[t.resource]}/s e um terreno adicional.</p>
  ${lock?`<p class="ritual-lock">${icon('lock')}${lock}</p>`:''}${owned?'<p class="territory-owned">Território da tribo. O novo terreno está disponível em Construir.</p>':order?`<p>${orderTitle(order)} · <span data-until="${order.until}"></span></p>`:seen?`<button class="primary" data-claim-territory="${t.id}" ${costAttr(t.cost)} data-max="${!!lock||constructionCount(s)>=builderCount(s)}">Estabelecer posto<span class="cost">${civicCost(t.cost)}</span></button>`:`<button class="primary" data-scout-territory="${t.id}" ${costAttr({wood:0,food:t.era*20,stone:0,spirit:0})} data-max="${!!lock||v.orders.some(o=>o.kind==='scout')}">Reconhecer a mata · ${Math.round(t.scout*(1-.15*v.research.tracking))}s<span class="cost">${t.era*20} alimento</span></button><p class="civic-note">Um aldeão deixa seu ofício durante o reconhecimento e volta ao concluir. A descoberta traz ${35*t.era} ${RESOURCE_NAMES[t.resource]} uma única vez.</p>`}</article>${orderQueue(s)}`;
}
export function researchPanel(s:GameState):string {
  return heading('Conhecimento da tribo','PESQUISAS E DEFESA','Escolha como a aldeia cresce. Cada pesquisa tem três níveis e continua fora do jogo.')+
  `<div class="research-list">${Object.entries(RESEARCH).map(([id,d])=>{const level=s.settlement.research[id as ResearchId],order=s.settlement.orders.find(o=>o.kind==='research'&&o.target===id);return`<article><h3>${d.name} <small>${level}/3</small></h3><p>${d.description}</p>${order?`<p class="research-running">Pesquisando · <span data-until="${order.until}"></span></p>`:`<button class="outline-button" data-research="${id}" ${costAttr(researchCost(s,id as ResearchId))} data-max="${level>=3||s.villageLevel<d.era}">${level>=3?'Conhecimento completo':s.villageLevel<d.era?`Exige Era ${d.era}`:'Pesquisar'}<span class="cost">${civicCost(researchCost(s,id as ResearchId))}</span></button>`}</article>`;}).join('')}</div>
  <p class="civic-note">Defesa atual: ${Math.round(raidProtection(s)*100)}% menos perdas em incursões ignoradas ou perdidas. Defender com os heróis continua sendo a forma de vencer a incursão.</p>${Object.values(s.settlement.sites).includes('market')?`<section class="trade-command"><h3>Casa de trocas</h3><label>Entregar<select id="trade-from" aria-label="Recurso para entregar"><option value="wood">100 madeira</option><option value="food">100 alimento</option><option value="stone">100 pedra</option></select></label><label>Receber<select id="trade-to" aria-label="Recurso para receber"><option value="food">65 alimento</option><option value="wood">65 madeira</option><option value="stone">65 pedra</option></select></label><button class="outline-button" data-village-trade>Realizar troca</button></section>`:''}${orderQueue(s)}`;
}

export function armyCoach(s:GameState,heroUid:string|null,trait:string,fighting=false):string {
  const enemy=enemyAdvice(s);
  const party=activeArmy(s),counts=countTraits(party.map(h=>h.characterId)),focus=s.settlement.focusTraits;
  const hero=s.heroes.find(h=>h.uid===heroUid)??party[0]??s.heroes[0],c=characters.find(c=>c.id===hero.characterId)!,role=roleOf(c),guide=ROLE_GUIDE[role],items=itemAdvice(s,hero),suggestions=armySuggestions(s),plan=recommendedParty(s);
  const selected=TRAIT_RULES[trait]?trait:'Caçador',rule=TRAIT_RULES[selected],status=traitStatus(selected,counts.get(selected)??0);
  const members=characters.filter(c=>c.traits.includes(selected));
  return `<div class="army-coach"><header><p class="eyebrow">CONSELHO DE GUERRA</p><h2>Faça a tribo lutar em conjunto</h2><p>Função define o posicionamento. Povos e espíritos criam laços. Experiência e ritualística continuam guiando os despertares.</p></header><div class="army-overview"><span><strong>${party.length}/${2+s.villageLevel}</strong> disponíveis no campo</span><span><strong>${[...counts].filter(([n,v])=>traitStatus(n,v).tier>0).length}</strong> laços ativos</span><span><strong>${party.length?Math.round(party.reduce((a,h)=>a+h.level,0)/party.length):0}</strong> experiência média</span></div>
  <div class="coach-layout"><section><h3>Seu plano de combate</h3><div class="army-presets">${[['Presas','Caçador'],['Manada','Guardião'],['Enxame','Invocador']].map(p=>`<button data-army-preset="${p.join(',')}">${p.join(' + ')}</button>`).join('')}</div><p class="civic-note">Prioridades: ${focus.length?focus.map(esc).join(' + '):'formação equilibrada'}. Escolha até dois laços no guia ao lado.</p><details class="enemy-advice"><summary>Preparar contra ${enemy.name}</summary><p>${enemy.roles.map(r=>`${r.count} ${ROLE_GUIDE[r.role].name}`).join(' · ')}</p>${enemy.tips.map(t=>`<p>${t}</p>`).join('')}</details>
  <div class="coach-warnings">${armyWarnings(s).map(w=>`<p>${icon('circle-help')}${esc(w)}</p>`).join('')||'<p>As funções básicas estão cobertas. Ajuste os laços e os itens ao desafio.</p>'}</div>
  <h3>Formação sugerida</h3><div class="suggested-party">${plan.map(h=>{const c=characters.find(c=>c.id===h.characterId)!;return`<button data-coach-hero="${h.uid}" aria-label="Analisar ${c.name}">${portraitHTML(c,h.stars)}<span>${c.name}<small>${ROLE_GUIDE[roleOf(c)].name}</small></span></button>`;}).join('')||'<p>Disponibilize heróis na aldeia para receber sugestões.</p>'}</div><div class="coach-actions"><button class="primary" data-action="apply-army-plan" data-lock-battle="1" ${s.paused||fighting?'disabled':''}>Aplicar plano e posições</button><button class="outline-button" data-action="formation">Ajustar casas manualmente</button></div><p class="civic-note">O plano usa companheiros na aldeia que estão fora do trabalho. É uma orientação baseada em atributos, funções e laços.</p>
  <h3>Companheiros que ajudam agora</h3>${suggestions.map(v=>{const c=characters.find(c=>c.id===v.hero.characterId)!;return`<article class="coach-suggestion"><div>${portraitHTML(c,v.hero.stars)}<span><b>${c.name}</b><small>${v.replace?`No lugar de ${characters.find(c=>c.id===v.replace!.characterId)!.name}`:'Preenche uma vaga livre'}</small></span></div><p>${v.gained.length?`Fortalece: ${v.gained.map(esc).join(', ')}.`:'Acrescenta atributos e uma opção de função.'}${v.lost.length?` Perde: ${v.lost.map(esc).join(', ')}.`:''}</p><button class="text-button" data-advisor-deploy="${v.hero.uid}" ${v.replace?`data-replace-hero="${v.replace.uid}"`:''} ${s.paused||fighting?'disabled':''}>Usar na formação</button></article>`;}).join('')||'<p class="muted">Não há companheiros livres na reserva. O catálogo da tribo mostra quem pode ser acolhido.</p>'}
  <h3>Laços próximos de despertar</h3><div class="near-traits">${nearTraits(s).filter(t=>!t.complete).slice(0,5).map(t=>`<button data-coach-trait="${esc(t.name)}"><b>${esc(t.name)}</b><span>${t.count}/${t.next} · faltam ${t.missing}</span><small>${t.recruits.length?`Pode acolher: ${t.recruits.slice(0,3).map(c=>c.name).join(', ')}`:'Confira os membros no guia de laços.'}</small></button>`).join('')}</div></section>
  <section class="coach-guides"><h3>Entenda as classes e os laços</h3><label>Escolha um laço<select id="coach-trait" aria-label="Laço para analisar">${Object.entries(TRAIT_RULES).map(([name,r])=>`<option value="${esc(name)}" ${name===selected?'selected':''}>${esc(name)} · ${r.kind}</option>`).join('')}</select></label><article class="trait-guide"><h4>${esc(selected)} <small>${status.count} na formação</small></h4>${rule.thresholds.map((n,i)=>`<p class="${status.count>=n?'unlocked':''}"><b>${n} membros</b> ${esc(rule.effects[i])}</p>`).join('')}<button class="outline-button" data-army-focus="${esc(selected)}" aria-pressed="${focus.includes(selected)}">${focus.includes(selected)?'Remover prioridade':'Priorizar este laço'}</button><div class="trait-members">${members.map(c=>{const h=s.heroes.find(h=>h.characterId===c.id);return`<button ${h?`data-coach-hero="${h.uid}"`:`data-character="${c.id}"`}><span>${c.name}</span><small>${h?h.away?'Em atividade':h.work?'Trabalhando':h.slot!==null?'No campo':'Na reserva':`Catálogo · custo ${c.cost}`}</small></button>`;}).join('')}</div></article>
  <h3>Função e equipamento</h3><select id="coach-hero" aria-label="Herói para analisar">${s.heroes.map(h=>`<option value="${h.uid}" ${h.uid===hero.uid?'selected':''}>${characters.find(c=>c.id===h.characterId)!.name}</option>`).join('')}</select><article class="hero-coaching"><div>${portraitHTML(c,hero.stars)}<span><h4>${c.name}</h4><b>${guide.name}</b><small>${guide.position}</small></span></div><p>${guide.description}</p><p class="civic-note">Habilidade: ${c.ability.name}. ${esc(c.ability.description)}</p><h4>Da sua bolsa</h4>${items.owned.map(({item,index})=>`<button class="advisor-item" data-advisor-equip="${hero.uid}:${index}" ${hero.items.length>=3||s.paused||fighting?'disabled':''}><span><b>${item.name}</b><small>${item.text}</small></span>${icon('plus')}</button>`).join('')||'<p class="muted">Expedições e a Forja de Osso trazem componentes.</p>'}<h4>Receitas que você pode formar</h4>${items.recipes.map(v=>`<button class="advisor-item" data-advisor-recipe="${v.a}:${v.b}" ${s.buildings.forge===0||s.paused||fighting?'disabled':''}><span><b>${v.item.name}</b><small>${itemById(s.inventory[v.a])!.name} + ${itemById(s.inventory[v.b])!.name}</small></span>${icon('anvil')}</button>`).join('')||'<p class="muted">Reúna dois componentes na bolsa para ver combinações possíveis.</p>'}<p class="civic-note">Itens úteis para esta função: ${items.ideal.map(i=>i.name).join(', ')}. Os efeitos completos estão no Códice.</p></article></section></div></div>`;
}
